### ISSUE TITLE
alpha 0.2.0 feature checklist

### ISSUE THREAD

**Issue by JanNitschke** [Onebeats/Elementaryengine#3]
Features that need to be in alpha 0.2.0:
- [x] Modular renderer
- [x] New asset structure
- [x] HUD 
- [x] Text rendering
- [ ] Basic netcode
- [x] Openworld
- [x] Levelstreaming
- [x] Restructured render code
- [ ] Skybox
- [ ] Fix directional light 
- [x] Own physics Thread
- [ ] Multithread support for renderer (Especialy MDI)

Features that may be in alpha 0.2.0:
- [ ] Post-processing optimisation
- [ ] DOF effect
- [ ] Level saving and loading
- [ ] Restructured imports for easier builds
- [ ] Switching to non-debugging binarys
- [ ] JavaScript expandable render pipeline
